In [1]:
 import pandas as pd
import numpy as np

In [2]:
data = {
    "StudentID": ["S001","S002","S003","S004","S005","S006","S007","S008","S009","S010"],
    "Name": ["Arjun Mehta","Divya Sharma","Karan Patel","Meera Nair","Sahil Gupta",
             "Anjali Singh","Rohan Verma","Pooja Yadav","Vivek Kumar","Nisha Agarwal"],
    "Age": [21,22,20,23,21,22,20,23,21,22],
    "City": ["Delhi","Mumbai","Pune","Chennai","Delhi",
             "Jaipur","Mumbai","Chennai","Pune","Delhi"],
    "Department": ["CSE","ECE","CSE","MECH","ECE",
                   "CSE","MECH","CSE","ECE","MECH"],
    "Score": [78,91,55,42,88,35,67,92,71,58],
    "Grade": ["B","A","C","D","A","F","B","A","B","C"],
    "Passed": [True,True,True,True,True,False,True,True,True,True]
}

df = pd.DataFrame(data)

df

  StudentID           Name  Age     City Department  Score Grade  Passed
0      S001    Arjun Mehta   21    Delhi        CSE     78     B    True
1      S002   Divya Sharma   22   Mumbai        ECE     91     A    True
2      S003    Karan Patel   20     Pune        CSE     55     C    True
3      S004     Meera Nair   23  Chennai       MECH     42     D    True
4      S005    Sahil Gupta   21    Delhi        ECE     88     A    True
5      S006   Anjali Singh   22   Jaipur        CSE     35     F   False
6      S007    Rohan Verma   20   Mumbai       MECH     67     B    True
7      S008    Pooja Yadav   23  Chennai        CSE     92     A    True
8      S009    Vivek Kumar   21     Pune        ECE     71     B    True
9      S010  Nisha Agarwal   22    Delhi       MECH     58     C    True

Load & **Inspect**

In [3]:
df.shape

(10, 8)

In [4]:
df.columns

Index(['StudentID', 'Name', 'Age', 'City', 'Department', 'Score', 'Grade',
       'Passed'],
      dtype='object')

In [5]:
df.dtypes

StudentID     object
Name          object
Age            int64
City          object
Department    object
Score          int64
Grade         object
Passed          bool
dtype: object

In [6]:
df.head(5)

  StudentID          Name  Age     City Department  Score Grade  Passed
0      S001   Arjun Mehta   21    Delhi        CSE     78     B    True
1      S002  Divya Sharma   22   Mumbai        ECE     91     A    True
2      S003   Karan Patel   20     Pune        CSE     55     C    True
3      S004    Meera Nair   23  Chennai       MECH     42     D    True
4      S005   Sahil Gupta   21    Delhi        ECE     88     A    True

In [7]:
df.tail(3)

  StudentID           Name  Age     City Department  Score Grade  Passed
7      S008    Pooja Yadav   23  Chennai        CSE     92     A    True
8      S009    Vivek Kumar   21     Pune        ECE     71     B    True
9      S010  Nisha Agarwal   22    Delhi       MECH     58     C    True

Q2. info() and describe()**bold text**

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   10 non-null     object
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   City        10 non-null     object
 4   Department  10 non-null     object
 5   Score       10 non-null     int64
 6   Grade       10 non-null     object
 7   Passed      10 non-null     bool
dtypes: bool(1), int64(2), object(5)
memory usage: 702.0+ bytes

In [9]:
df["Score"].mean()

np.float64(67.7)

In [10]:
df["Score"].std()

20.13316776973868

Column **Access**

In [11]:
df["Name"]

0      Arjun Mehta
1     Divya Sharma
2      Karan Patel
3       Meera Nair
4      Sahil Gupta
5     Anjali Singh
6      Rohan Verma
7      Pooja Yadav
8      Vivek Kumar
9    Nisha Agarwal
Name: Name, dtype: object

In [12]:
df[["Score","Grade"]]

   Score Grade
0     78     B
1     91     A
2     55     C
3     42     D
4     88     A
5     35     F
6     67     B
7     92     A
8     71     B
9     58     C

Q4. **loc**

In [13]:
df.loc[0]

StudentID            S001
Name          Arjun Mehta
Age                    21
City                Delhi
Department            CSE
Score                  78
Grade                   B
Passed               True
Name: 0, dtype: object

In [14]:
df.loc[2:5]

  StudentID          Name  Age     City Department  Score Grade  Passed
2      S003   Karan Patel   20     Pune        CSE     55     C    True
3      S004    Meera Nair   23  Chennai       MECH     42     D    True
4      S005   Sahil Gupta   21    Delhi        ECE     88     A    True
5      S006  Anjali Singh   22   Jaipur        CSE     35     F   False

In [15]:
df.loc[0:4, ["Name","Score","Grade"]]

           Name  Score Grade
0   Arjun Mehta     78     B
1  Divya Sharma     91     A
2   Karan Patel     55     C
3    Meera Nair     42     D
4   Sahil Gupta     88     A

Q5. **iloc**

In [16]:
df.iloc[:3]

  StudentID          Name  Age    City Department  Score Grade  Passed
0      S001   Arjun Mehta   21   Delhi        CSE     78     B    True
1      S002  Divya Sharma   22  Mumbai        ECE     91     A    True
2      S003   Karan Patel   20    Pune        CSE     55     C    True

In [17]:
df.iloc[-2:]

  StudentID           Name  Age   City Department  Score Grade  Passed
8      S009    Vivek Kumar   21   Pune        ECE     71     B    True
9      S010  Nisha Agarwal   22  Delhi       MECH     58     C    True

In [18]:
df.iloc[[1,3,5],[0,2,4]]

  StudentID  Age Department
1      S002   22        ECE
3      S004   23       MECH
5      S006   22        CSE

**Q6. Boolean Filter**

In [19]:
high_score = df[df["Score"] > 80]
high_score

  StudentID          Name  Age     City Department  Score Grade  Passed
1      S002  Divya Sharma   22   Mumbai        ECE     91     A    True
4      S005   Sahil Gupta   21    Delhi        ECE     88     A    True
7      S008   Pooja Yadav   23  Chennai        CSE     92     A    True

In [20]:
high_score.shape[0]

3

Q7. Delhi + **CSE**

In [21]:
df[(df["City"]=="Delhi") & (df["Department"]=="CSE")][["Name","Score","Grade"]]

          Name  Score Grade
0  Arjun Mehta     78     B

Q8. Failed **Students**

In [22]:
failed = df[df["Passed"] == False]
failed

  StudentID          Name  Age    City Department  Score Grade  Passed
5      S006  Anjali Singh   22  Jaipur        CSE     35     F   False

Average Score

In [23]:
failed["Score"].mean()

np.float64(35.0)

Q9. Name Contains "a"

In [24]:
df[df["Name"].str.contains("a", case=False)]

  StudentID           Name  Age     City Department  Score Grade  Passed
0      S001    Arjun Mehta   21    Delhi        CSE     78     B    True
1      S002   Divya Sharma   22   Mumbai        ECE     91     A    True
2      S003    Karan Patel   20     Pune        CSE     55     C    True
3      S004     Meera Nair   23  Chennai       MECH     42     D    True
4      S005    Sahil Gupta   21    Delhi        ECE     88     A    True
5      S006   Anjali Singh   22   Jaipur        CSE     35     F   False
6      S007    Rohan Verma   20   Mumbai       MECH     67     B    True
7      S008    Pooja Yadav   23  Chennai        CSE     92     A    True
8      S009    Vivek Kumar   21     Pune        ECE     71     B    True
9      S010  Nisha Agarwal   22    Delhi       MECH     58     C    True

Q10. Add New **Column**

In [25]:
df["Score_Category"] = np.where(
    df["Score"] >= 80,
    "Distinction",
    np.where(
        df["Score"] >= 60,
        "Merit",
        "Pass/Fail"
    )
)

df

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
0,S001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
1,S002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
2,S003,Karan Patel,20,Pune,CSE,55,C,True,Pass/Fail
3,S004,Meera Nair,23,Chennai,MECH,42,D,True,Pass/Fail
4,S005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction
5,S006,Anjali Singh,22,Jaipur,CSE,35,F,False,Pass/Fail
6,S007,Rohan Verma,20,Mumbai,MECH,67,B,True,Merit
7,S008,Pooja Yadav,23,Chennai,CSE,92,A,True,Distinction
8,S009,Vivek Kumar,21,Pune,ECE,71,B,True,Merit
9,S010,Nisha Agarwal,22,Delhi,MECH,58,C,True,Pass/Fail